name: Bug report
description: Report a problem
labels: [ "bug" ]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us what you expected to happen.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      placeholder: 0.1.0
  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps
      description: Minimal steps or code snippet to reproduce